### ISSUE TITLE
Return value of the Time_measurement class not numeric

### ISSUE THREAD

**Issue by spickartz** [fast-project/fast-lib#15]
The Time_measurement class is returning something like:

``` yaml

---
result: vm migrated
list:
  - vm-name: centos7-page-zeroing
    status: success
    time-measurement:
      reattach-pci-devs: " 0.000005s wall, 0.000000s user + 0.000000s system = 0.000000s CPU (n/a%)\n"
      migrate: " 2.937765s wall, 0.000000s user + 0.000000s system = 0.000000s CPU (n/a%)\n"
      detach-pci-devs: " 0.005058s wall, 0.000000s user + 0.000000s system = 0.000000s CPU (n/a%)\n"
      overall: " 3.134154s wall, 0.020000s user + 0.020000s system = 0.040000s CPU (1.3%)\n"

---
```

I would rather expect to receive seconds (i.e., the wall clock time)
